apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-smsldpcz
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-smsldpcz:6faa99fbad6ce2afb34ca561edef337237dc690c@sha256:064d021b0a0b286870f39b03e98ce4d72927182e11f0e7c638f1c0ee712c7381
          name: container-image
